### ISSUE TITLE
Acceptance/smoke test suites

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry-community/haproxy-boshrelease#16]
This release needs some tests to verify functionality is working as desired.

Things to consider:
app ssh access
gzip compression testing
force-https redirecting
tunnel timeouts for websockets over 443
handling x-forwarded-for and x-forwarded-proto/port headers properly
backend server connection tests
whatever else i can think of

**Comment by mridhuljp** [comment]
@geofffranks  : Could you please share some inputs on the testing plan / approach ?

**Comment by geofffranks** [comment]
I was thinking of having a bosh errand to run smoke tests  to verify the above functionality, that could be run after deploying cf-ha-proxy in front of a backend that was set up to facilitate the testing.. maybe a separate bosh release for that and the tests. then our CI pipeline would deploy both, run the tests, and validate the new version of cf-haproxy?

**Comment by geofffranks** [comment]
Closing this since no progress has been made in over a year
