### ISSUE TITLE
Rename the boshrelease?

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry-community/haproxy-boshrelease#30]
There can be some significant confusion when talking about this boshrelease in contrast with the haproxy job provided by cf-release, as it's the "CF HAProxy boshrrelease" (do you mean the cf-release's HAProxy, or cf-haproxy-boshrelease"?)

Should we rename this to something a little less confusing, perhaps loadbalancer-boshrelease, or haproxy-boshrelease, or some other name?

**Comment by shinji62** [comment]
+1 for haproxy-boshrelease.

**Comment by jhunt** [comment]
I'd prefer something a little more unique, like cloudfront-boshrelease or cloudgate-boshrelease, since it's not a general purpose haproxy release.

**Comment by shinji62** [comment]
It's haproxy software no more no less ..

**Comment by poblin-orange** [comment]
Hello,
id say haproxy-boshrelease, loadbalancer is way much too generic, IHMO
Pierre

**Comment by jhunt** [comment]
I was under the impression that there were CF-specific bits in this release, but if that is not the case, I guess `haproxy-boshrelease` is okay, but it won't solve my particular issue with clients confusing `haproxy` job in `cf` with the `haproxy` BOSH release 😞

**Comment by geofffranks** [comment]
I thought there was some stuff specific to app_ssh, but that's just generic tcp connection routing after all. The main CF-ness is similarly named properties, and descriptions in the job spec referencing "Routers".

**Comment by axelfauvel** [comment]
+1 for haproxy-boshrelease

**Comment by geofffranks** [comment]
Looks like the haproxy-boshrelease's have it

**Comment by geofffranks** [comment]
Renamed + released. I updated our CI environment, the genesis index, and requested an update on bosh.io.
