### ISSUE TITLE
Make manifest on openstack

### ISSUE THREAD

**Issue by 7CHANHO** [cloudfoundry-community/haproxy-boshrelease#31]
## Issue
I tried to make manifest on openstack infrastructure using 'make_manifest' script.
But It does'n work. I did not use this script file, so it took a lot of work to make a manifest file.

## Solution
I've modified it can make a manifest on openstack infrastructure.
The biggest difference from the previous one is that the cf manifest file is merged.

### Usage
1. Customise your deployment stub
```
$ vi templates/stub.yml
$ vi templates/jobs.yml
```
2. Run make_manifest
```
$ ./templates/make_manifest openstack 10.10.0.10 cf.yml
```
3. Deploy!
```
$ bosh deploy
```

## Proposal
Could you please check if I can PR and commit this?
If you accept it, I will sign and send CLA.
https://github.com/7CHANHO/cf-haproxy-boshrelease

**Comment by geofffranks** [comment]
No CLA needed for the cloudfoundry-community repos. Feel free to submit a PR and we can review the changes

**Comment by 7CHANHO** [comment]
Thank you!
I submit a PR #32.
Please review the change.
