### ISSUE TITLE
What is the keepalive_timeout attribute for?

### ISSUE THREAD

**Issue by YunSangJun** [cloudfoundry-community/haproxy-boshrelease#35]
What is the keepalive_timeout attribute for?

I can not find keepalived package and configuration file.

Do you have plan to develop keepalived feature?.

**Comment by geofffranks** [comment]
It's used in https://github.com/cloudfoundry-community/haproxy-boshrelease/blob/master/jobs/haproxy/templates/haproxy.config.erb#L23

HAProxy documentation: https://cbonte.github.io/haproxy-dconv/configuration-1.6.html#4-timeout%20http-keep-alive

**Comment by YunSangJun** [comment]
I was confused with keepalivedc.

Actually, i am using haproxy-boshrelease with keepalivedc to achieve high availability. 
To automate this feature, need to add some settings to haproxy-boshrelease.

Do you have plan to develop this feature like keepalivedc?.

http://www.keepalived.org/
http://www.stratoscale.com/wp-content/uploads/HAproxy-architecture.png

**Comment by gberche-orange** [comment]
Orange is preparing a PR for keep-alived support in haproxy-boshrelease. We're polishing the documentation and should submit the PR soon. Some more details at https://github.com/orange-cloudfoundry/cf-haproxy-boshrelease/pull/1 

/CC @axelfauvel @poblin-orange
